doc: update doc (compression param)
ign-packo/Apply_ACV pull request #8
Opened 2022-06-07 11:52 UTC by nlenglet-ign

Mise à jour et clarification de la doc (notamment concernant le paramètre de compression)

2022-06-07 12:13 UTC, amrosu requested changes

2022-06-07 12:13 UTC, amrosu commented on README.md
> +                        input image data folder
Mettre sur la même ligne nom param et description (valable pour toute la partie aide)

2022-06-07 12:13 UTC, amrosu commented on README.md
>  ````
corriger ' -> `

2022-06-07 12:13 UTC, amrosu commented on README.md
> +  -f FILE, --file FILE  output file containing command lines (cmd.txt)
metrre en paranthèse "default:"

2022-06-07 12:13 UTC, amrosu commented on README.md
> +                        JPEG Compression quality (default=90)
pour rester cohérent, mettre ": "

2022-06-07 12:13 UTC, amrosu commented on apply_acv.py
> +        help="Jpeg compression quality (default=100, no compression)",
"=" -> ":"

2022-06-07 12:17 UTC, nlenglet-ign commented on README.md
> +                        JPEG Compression quality (default=90)
Fait

2022-06-07 12:17 UTC, nlenglet-ign commented on README.md
> +  -f FILE, --file FILE  output file containing command lines (cmd.txt)
Fait

2022-06-07 12:18 UTC, nlenglet-ign commented on README.md
>  ````
Fait

2022-06-07 12:18 UTC, nlenglet-ign commented on README.md
> +                        input image data folder
Fait

2022-06-07 12:18 UTC, nlenglet-ign commented on apply_acv.py
> +        help="Jpeg compression quality (default=100, no compression)",
Fait

2022-06-07 12:31 UTC, amrosu requested changes

2022-06-07 12:31 UTC, amrosu commented on README.md
> +  -b BLOCKSIZE, --blocksize BLOCKSIZE   number of lines per block
mettre valeur par défaut (1000)

2022-06-09 08:14 UTC, amrosu approved these changes
Avant de faire le fusion, corriger le contenu de l'aide et assurer sa cohérence avec le contenu des scripts

2022-06-09 08:14 UTC, amrosu commented on README.md
> +  -a ACV, --acv ACV     path of folder containing acv files and masks
mettre en accord avec la définition donnée dans le script

2022-06-09 08:28 UTC, merged